import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Logo from '../public/logo.svg'
import { useRouter } from 'next/router'
import { AiFillGithub } from 'react-icons/ai'
import { BsMoonFill } from 'react-icons/bs'
import { HiDotsVertical } from 'react-icons/hi'

export default function Home() {
  const router = useRouter()
  const [open, setOpen] = useState(false)

  return (
    <div>
      <Head>
        <title>
          Serity UI - Rapidly build modern websites with easy-to-use React
          components
        </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <main className='h-screen pt-6 after:bg-white/[0.15] bg-gradient-to-r from-blue-700 via-blue-800 to-blue-600'>
        <header className='h-16 w-11/12 mx-auto rounded-lg bg-white/[0.15]'>
          <div className='flex items-center justify-between h-full px-7 flex-wrap w-full'>
            <Image
              className='text-white'
              alt='Serity UI logo'
              src={Logo}
              width={26}
              height={26}
            />

            <HiDotsVertical
              className='lg:hidden block h-5 w-5 cursor-pointer text-white'
              onClick={() => setOpen(!open)}
            />

            <nav className={`${open ? 'block' : 'hidden'} lg:block`}>
              <ul className='lg:flex lg:gap-7'>
                <li>
                  <Link
                    className='text-white block hover:text-[rgba(56,189,248,1)]'
                    href='/docs/installation/'
                  >
                    Docs
                  </Link>
                </li>
                <li>
                  <Link
                    className='text-white block hover:text-[rgba(56,189,248,1)]'
                    href='https://github.com/edman-cota/serity-ui.com'
                  >
                    Components
                  </Link>
                </li>
                <div className='w-[1px] h-6 bg-slate-300'></div>
                <li>
                  <Link
                    className='text-white flex items-center'
                    href='https://github.com/edman-cota/serity-ui.com'
                  >
                    <BsMoonFill />
                  </Link>
                </li>
                <li>
                  <Link
                    className='text-white flex items-center'
                    target='_blank'
                    href='https://github.com/serity-ui/serity-ui'
                  >
                    <AiFillGithub />
                  </Link>
                </li>
              </ul>
            </nav>
          </div>
        </header>
        <div className='flex flex-col w-11/12 h-[calc(100vh_-_90px)] mx-auto lg:flex-row'>
          <div className='flex flex-col w-full py-12 justify-center lg:w-[45%]'>
            <h1 className='text-white text-3xl font-bold text-center md:text-5xl lg:text-left lg:mb-5 '>
              Rapidly build modern websites with easy-to-use React components
            </h1>
            <p className='text-white py-10 text-xl text-center lg:text-left'>
              Easy-to-setup React UI components to speed up your development and
              focus only on the things that matter
            </p>
            <button
              onClick={() => router.push('docs/installation')}
              className='bg-blue-600 text-white px-5 py-2 rounded-md mt-4 w-44 h-10 mx-auto lg:mx-0 '
            >
              Get Started
            </button>
          </div>
          <div className='w-full lg:w-[55%]'></div>
        </div>
      </main>
    </div>
  )
}
