import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav className="h-20 w-11/12 mx-auto rounded-lg mt-8 backdrop-blur-sm bg-white/[0.25] ">
          <ul className="flex items-center justify-center  h-full px-5">
            <li className="text-white text-xl">Coming Soon</li>
          </ul>
        </nav>
      </main>
    </div>
  );
}
